version: '3.8'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: api/Dockerfile
    ports:
      - "8080:8080"
    networks:
      - api-net
    depends_on:
      - redis

  worker:
    container_name: worker
    build:
      context: .
      dockerfile: worker/Dockerfile
    ports:
      - "8081:8080"
    networks:
      - api-net
    depends_on:
      - redis

  redis:
    container_name: test-redis
    image: redis:5.0.5
    ports:
      - "6379:6379"
    networks:
      - api-net

networks:
  api-net:
    driver: bridge